import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/header";
import { TopBar } from "@/components/top-bar";
import { BackToTop } from "@/components/back-to-top";
import NextTopLoader from "nextjs-toploader";
import { getDictionary } from "./dictionaries";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LangLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ lang: string }>;
}) {
  const { lang } = await params;
  const dictionary = await getDictionary(lang as "en" | "zh");

  return (
    <html lang={lang} suppressHydrationWarning>
      <body>
        <NextTopLoader
          color="var(--primary-red)"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="cubic-bezier(0.4, 0, 0.2, 1)"
          speed={200}
          shadow="0 0 10px var(--primary-red), 0 0 20px rgba(237, 37, 78, 0.3)"
          zIndex={1031}
        />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />
          <Header dictionary={dictionary} lang={lang} />
          <main>{children}</main>
          <BackToTop />
        </ThemeProvider>
      </body>
    </html>
  );
}
